config/routes.rb
Rails.application.routes.draw do
  resources :groups do
    resources :spendings
  end

  devise_for :users
  root to: 'home#index'

  get 'home', to: 'home#index'
  
  resources :users, only: [:index, :show] do
  end
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    can :manage, :all if user == current_user

    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true
  validates :icon, presence: true
  validates :name, uniqueness: true

  has_many :group_spendings, dependent: :destroy
  has_many :spendings, through: :group_spendings
end

app/models/group_spending.rb
class GroupSpending < ApplicationRecord
  validates :group_id, presence: true
  validates :spending_id, presence: true

  belongs_to :group
  belongs_to :spending
end

app/models/spending.rb
class Spending < ApplicationRecord
  belongs_to :author, class_name: 'User'
  validates :name, presence: true
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }

  has_many :group_spendings, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :groups, dependent: :destroy
  has_many :spendings, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def after_sign_in_path_for(_resource)
    groups_path
  end

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :çpassword_confirmation) }
    # devise_parameter_sanitizer
    # .permit(:account_update) { |u| u.permit(:name, :surname, :email, :password, :current_password)}
  end
end

app/controllers/groups_controller.rb
require 'compass-rails'

class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: %i[show edit update destroy]

  # GET /groups or /groups.json
  def index
    @groups = Group.includes([group_spendings: :spending]).where(author_id: current_user.id)
  end

  # GET /groups/1 or /groups/1.json
  def show; end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)

    unless asset?(@group.icon)
      flash[:notice] = 'You should select an existing icon eg. icon1.png, icon2.png, icon3.png'
      redirect_to request.referrer
      return
    end

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_path, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon, :author_id)
  end

  def asset?(path)
    (Rails.application.assets || ::Sprockets::Railtie.build_environment(Rails.application)).find_asset(path) != nil
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/spendings_controller.rb
class SpendingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_spending, only: %i[show edit update destroy]

  # GET /spendings or /spendings.json
  def index
    @spendings = Spending.joins(:group_spendings)
      .where(group_spendings: { group_id: params[:group_id] }).order(created_at: :desc)
    @group = Group.find(params[:group_id])
  end

  # GET /spendings/1 or /spendings/1.json
  def show; end

  # GET /spendings/new
  def new
    @spending = Spending.new
  end

  # GET /spendings/1/edit
  def edit; end

  # POST /spendings or /spendings.json
  def create
    @spending = Spending.new(author_id: spending_params[:author_id], name: spending_params[:name],
                             amount: spending_params[:amount])

    unless params[:spending][:group_ids]
      flash[:notice] = 'You should select at least one category'
      redirect_to request.referrer
      return
    end

    respond_to do |format|
      if @spending.save

        params[:spending][:group_ids].each do |group_id|
          puts group_id
          GroupSpending.create!(group_id: group_id.to_i, spending_id: @spending.id)
        end

        format.html { redirect_to group_spendings_url, notice: 'Spending was successfully created.' }
        format.json { render :show, status: :created, location: @spending }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @spending.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spendings/1 or /spendings/1.json
  def update
    respond_to do |format|
      if @spending.update(spending_params)
        format.html { redirect_to spending_url(@spending), notice: 'Spending was successfully updated.' }
        format.json { render :show, status: :ok, location: @spending }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @spending.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spendings/1 or /spendings/1.json
  def destroy
    @spending.destroy

    respond_to do |format|
      format.html { redirect_to spendings_url, notice: 'Spending was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_spending
    @spending = Spending.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def spending_params
    params.require(:spending).permit(:author_id, :name, :amount, group_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/spendings_helper.rb
module SpendingsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.hidden_field :author_id, value: current_user.id%>
  </div>

  <div>
    <%= form.text_field :name, class: "form-control p-3", placeholder: "Name"  %>
  </div>

  <div>
    <%= form.text_field :icon, class: "form-control p-3", placeholder: "Icon"  %>
  </div>

  <div>
    <%= form.submit 'Save', class: "new-group-button bg-success text-white text-decoration-none form-control p-4 text-center" %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>">
<%= link_to group_spendings_path(group.id), class:"text-decoration-none text-dark shadow" do %>
 <div class="d-flex justify-content-between align-items-center bg-light m-3 p-2 single-group-card">

      <%= image_tag group.icon, :size => '100x100', id: "group_icon" %>
      <%= group.name %>
      <span class="fw-bold">
        $ <%=group.group_spendings.reduce(0) { |sum, group_spending| sum + (group_spending.spending.amount) }%>
      </span>
 </div>
<% end %>
 
</div>

app/views/groups/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark main-blue-background">
  <div class="container-fluid">
  
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <h3 class="text-white text-cener ms-auto">TRANSACTIONS</h3>
    <span class="material-icons navbar-brand ms-auto nav-search-icon">
      search
    </span>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
    </div>
    
  </div>
</nav>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/index.html.erb
<%= render 'shared/nav', name: "CATEGORIES"%>
<div id="groups">
  <div class="groups-wrapper">
    <% @groups.each do |group| %>
      <%= link_to group do  %>
        <%= render group %>
      <% end %>
    <% end %>
    <%= link_to "New Category", new_group_path , class:"new-group-button bg-success text-white text-decoration-none form-control p-4 text-center" %>
  </div>
</div>

app/views/groups/new.html.erb
<%= render 'shared/nav_with_back_button', name: "CREATE CATAGORY", path: groups_path  %>
<%= render "form", group: @group %>

app/views/groups/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @group %>

<div>
  <%= link_to "Edit this group", edit_group_path(@group) %> |
  <%= link_to "Back to groups", groups_path %>

  <%= button_to "Destroy this group", @group, method: :delete %>
</div>

app/views/home/index.html.erb
<main class="m-2">
    <h1 class="splash-title display-4 text-center">Budget</h1>
    <div class="registration-buttons">
        <%= button_to 'LOG IN' , new_user_session_path, class: "form-control btn main-blue-background text-light p-3", method: :get %>
        <%= button_to 'SIGN UP' ,new_user_registration_path ,  class: "form-control btn btn-muted p-3", method: :get%>
    </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons"/>
    
    
  </head>

  <body class="gray-bg">

    <% if notice%>
        <div class="alert alert-primary alert-dismissible fade show" role="alert">
      <%= notice %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <%end%>
    <% if alert%>
      <div class="alert alert-primary alert-dismissible fade show" role="alert">
      <%= alert %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <%end%>

    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  </body>
</html>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark main-blue-background">
  <div class="container-fluid">
  
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <h3 class="text-white text-cener ms-auto"><%= name%></h3>
    <span class="material-icons navbar-brand ms-auto nav-search-icon">
      search
    </span>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <%= button_to 'Log Out', destroy_user_session_path, method: :delete, class: "bg-transparent border-0 text-light"%>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_nav_with_back_button.html.erb
<nav class="main-blue-background d-flex justify-content-between align-items-end text-light login-page-nav p-3">
      <span>
        <%= link_to  path, class: "bg-transparent text-light border-0", :method => :get do%>
        <span class="material-icons nav-search-icon ">
        west
        </span>
      <%end%>
      </span>

      <span>
      <h2><%= name%></h2>
      </span>

      <span class="material-icons navbar-brand nav-search-icon">
        search
      </span>
     
</nav>

app/views/spendings/_form.html.erb
<%= form_with(model: spending, url:group_spendings_url(params[:group_id]), data: {turbo: false})  do |form| %>
  <% if spending.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(spending.errors.count, "error") %> prohibited this spending from being saved:</h2>

      <ul>
        <% spending.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 <div class="d-flex flex-wrap justify-content-center align-items-center p-2">
    <% Group.where(author_id: current_user.id).each_with_index do |g , i| %>
           <span class="px-1">
              <%= form.check_box :group_ids, {multiple: true}, g.id, nil %><%= g.name%>
           </span>
    <% end %>
 </div>

  <div>
    <%= form.hidden_field :author_id, value: current_user.id %>
  </div>

  <div>
    <%= form.text_field :name, class: "form-control p-3", placeholder: "Name"  %>
  </div>

  <div>
    <%= form.text_field :amount, class: "form-control p-3", placeholder: "Amount"  %>
  </div>

  <div>
    <%= form.submit 'Save', class: "new-group-button bg-success text-white text-decoration-none form-control p-4 text-center"  %>
  </div>
<% end %>

app/views/spendings/_spending.html.erb
<div id="<%= dom_id spending %>">

 <div class="d-flex justify-content-between align-items-center bg-light m-3 py-5 px-2">
       <%= spending.name %>
      <span class="fw-bold">
        $ <%= spending.amount %>
      </span>
 </div>
</div>

app/views/spendings/edit.html.erb
<h1>Editing spending</h1>

<%= render "form", spending: @spending %>

<br>

<div>
  <%= link_to "Show this spending", @spending %> |
  <%= link_to "Back to spendings", spendings_path %>
</div>

app/views/spendings/index.html.erb
<%= render 'shared/nav_with_back_button', name: "TRANSACTIONS", path: groups_path  %>


<div id="spendings">
  <div class="groups-wrapper">

  <div class="d-flex justify-content-between align-items-center bg-light p-2 m-3"> 
    <%= image_tag @group.icon, :size => '100x100' %>
    <span><%= @group.name%></span>
    <div class="fw-bold">
      $<%=@spendings.reduce(0) { |sum, spending| sum + spending.amount }%>
    </div>
  </div>

  <% @spendings.each do |spending| %>
    <%= render spending %>
  <% end %>
  </div>
    <%= link_to "New Transaction", new_group_spending_path(params[:group_id]) , class:"new-group-button bg-success text-white text-decoration-none form-control p-4 text-center" %>

</div>

app/views/spendings/new.html.erb
<%= render 'shared/nav_with_back_button', name: "NEW TRANSACTION", path: group_spendings_path  %>

<%= render "form", spending: @spending %>

app/views/spendings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @spending %>

<div>
  <%= link_to "Edit this spending", edit_group_spending_path(@spending) %> |
  <%= link_to "Back to spendings", group_spendings_path %>

  <%= button_to "Destroy this spending", group_spending_path(@spending), method: :delete %>
</div>